package com.example.data.ai

object ProjectTemplates {

    fun getRiceTradingTemplate(projectName: String): List<GeneratedFile> {
        return listOf(
            GeneratedFile(
                filePath = "src/index.html",
                language = "html",
                isMain = true,
                content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$projectName - AI Rice Trading Platform</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body { font-family: 'Plus Jakarta Sans', sans-serif; background-color: #0f172a; color: #f8fafc; }
    </style>
</head>
<body class="bg-slate-900 text-slate-100 min-h-screen">
    <div id="app"></div>
</body>
</html>
                """.trimIndent()
            ),
            GeneratedFile(
                filePath = "src/App.tsx",
                language = "typescript",
                content = """
import React, { useState } from 'react';
import Header from './components/Header';
import Dashboard from './components/Dashboard';
import Inventory from './components/Inventory';
import Orders from './components/Orders';

export default function App() {
    const [activeTab, setActiveTab] = useState<'dashboard' | 'inventory' | 'orders'>('dashboard');

    return (
        <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col">
            <Header activeTab={activeTab} setActiveTab={setActiveTab} />
            <main className="flex-1 p-6 max-w-7xl mx-auto w-full">
                {activeTab === 'dashboard' && <Dashboard />}
                {activeTab === 'inventory' && <Inventory />}
                {activeTab === 'orders' && <Orders />}
            </main>
            <footer className="border-t border-slate-800 p-4 text-center text-xs text-slate-500">
                Generated by EfraHope AI Builder • $projectName V1.0
            </footer>
        </div>
    );
}
                """.trimIndent()
            ),
            GeneratedFile(
                filePath = "src/components/Dashboard.tsx",
                language = "typescript",
                content = """
import React from 'react';

export default function Dashboard() {
    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-2xl font-bold text-white">Rice Trading Executive Dashboard</h1>
                    <p className="text-sm text-slate-400">Real-time inventory levels, market pricing & trade metrics</p>
                </div>
                <button className="bg-indigo-600 hover:bg-indigo-500 text-white px-4 py-2 rounded-lg text-sm font-medium transition">
                    + New Batch Trade
                </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="bg-slate-900 p-4 rounded-xl border border-slate-800">
                    <p className="text-xs text-slate-400">Total Rice Stock</p>
                    <p className="text-2xl font-bold text-emerald-400 mt-1">1,480 Metric Tons</p>
                </div>
                <div className="bg-slate-900 p-4 rounded-xl border border-slate-800">
                    <p className="text-xs text-slate-400">Monthly Trade Revenue</p>
                    <p className="text-2xl font-bold text-indigo-400 mt-1">${'$'}248,500</p>
                </div>
                <div className="bg-slate-900 p-4 rounded-xl border border-slate-800">
                    <p className="text-xs text-slate-400">Active Bulk Orders</p>
                    <p className="text-2xl font-bold text-amber-400 mt-1">34 Pending</p>
                </div>
                <div className="bg-slate-900 p-4 rounded-xl border border-slate-800">
                    <p className="text-xs text-slate-400">Avg Wholesale Price</p>
                    <p className="text-2xl font-bold text-cyan-400 mt-1">${'$'}720 / Ton</p>
                </div>
            </div>
        </div>
    );
}
                """.trimIndent()
            ),
            GeneratedFile(
                filePath = "src/components/Header.tsx",
                language = "typescript",
                content = """
import React from 'react';

interface HeaderProps {
    activeTab: string;
    setActiveTab: (tab: 'dashboard' | 'inventory' | 'orders') => void;
}

export default function Header({ activeTab, setActiveTab }: HeaderProps) {
    return (
        <header className="bg-slate-900 border-b border-slate-800 sticky top-0 z-10 px-6 py-4 flex items-center justify-between">
            <div className="flex items-center space-x-3">
                <span className="font-bold text-lg text-white">RiceTrade AI</span>
            </div>

            <nav className="flex space-x-2">
                {['dashboard', 'inventory', 'orders'].map(tab => (
                    <button
                        key={tab}
                        onClick={() => setActiveTab(tab as any)}
                        className="px-4 py-2 rounded-lg text-sm font-medium capitalize transition"
                    >
                        {tab}
                    </button>
                ))}
            </nav>
        </header>
    );
}
                """.trimIndent()
            ),
            GeneratedFile(
                filePath = "src/types/index.ts",
                language = "typescript",
                content = """
export interface RiceProduct {
    id: string;
    variety: string;
    grade: string;
    origin: string;
    quantityTons: number;
    pricePerTon: number;
}
                """.trimIndent()
            )
        )
    }

    fun getECommerceTemplate(projectName: String): List<GeneratedFile> {
        return listOf(
            GeneratedFile(
                filePath = "src/index.html",
                language = "html",
                isMain = true,
                content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$projectName - AI Storefront</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-slate-100">
    <div id="app"></div>
</body>
</html>
                """.trimIndent()
            ),
            GeneratedFile(
                filePath = "src/App.tsx",
                language = "typescript",
                content = """
import React, { useState } from 'react';

export default function App() {
    const [cartCount, setCartCount] = useState(0);

    return (
        <div className="min-h-screen bg-slate-950 text-slate-100 p-6">
            <header className="p-4 bg-slate-900 border-b border-slate-800 flex justify-between items-center">
                <h1 className="text-xl font-bold text-indigo-400">$projectName</h1>
                <div className="bg-indigo-600 px-3 py-1 rounded-full text-xs font-semibold">
                    Cart ({cartCount})
                </div>
            </header>
        </div>
    );
}
                """.trimIndent()
            )
        )
    }

    fun getGenericTemplate(projectName: String, appType: String, description: String): List<GeneratedFile> {
        return listOf(
            GeneratedFile(
                filePath = "src/index.html",
                language = "html",
                isMain = true,
                content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$projectName</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-slate-100">
    <div id="app"></div>
</body>
</html>
                """.trimIndent()
            ),
            GeneratedFile(
                filePath = "src/App.tsx",
                language = "typescript",
                content = """
import React from 'react';

export default function App() {
    return (
        <div className="min-h-screen bg-slate-950 text-slate-100 p-6">
            <h1 className="text-2xl font-bold text-white">$projectName</h1>
            <p className="text-slate-400 mt-2">$description</p>
        </div>
    );
}
                """.trimIndent()
            )
        )
    }
}
